server:
  port: 9001
  servlet:
    context-path: /
    session:
      cookie:
        name: JSESSIONID_MR_WEB

cis-service-security:
  oauth2:
    client:
      clientId: sampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9002/oauth/token
      scope: webclient

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: sampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9002/oauth/token
      userAuthorizationUri: http://localhost:9002/oauth/authorize
    resource:
      userInfoUri: http://localhost:9002/user/me

spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true